name: Devcontainer prebuilding

on:
  workflow_call:
    inputs:
      imageName:
        default: devcontainer
        description: Image name for the pre-built devcontainer
        required: false
        type: string
      imageTag:
        default: latest
        description: Image tag for the pre-built devcontainer
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pre-build devcontainer image
        uses: devcontainers/ci@v0.3
        if: ${{ hashFiles('./github/.devcontainer/**', './github/.devcontainer.json') != '' }}
        with:
          imageName: devcontainer
          imageTag: latest
          noCache: true
          push: true
          subFolder: .github
