name: Devcontainer prebuilding

on:
  workflow_call:
    inputs:
      imageName:
        description: Image name for the pre-built devcontainer
        required: true
        type: string
      imageTag:
        default: latest
        description: Image tag for the pre-built devcontainer
        required: false
        type: string
      subFolder:
        default: .github
        description: Path to the folder containing the devcontainer (the parent of `.devcontainer` folder or `.devcontainer.json` file)
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pre-build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ inputs.imageName }}
          imageTag: ${{ inputs.imageTag }}
          noCache: true
          push: always
          subFolder: ${{ inputs.subFolder }}
